(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(s){if(s.ep)return;s.ep=!0;const o=t(s);fetch(s.href,o)}})();const E=[];let l=1;const u=8,c={cardsContainer:document.querySelector(".block-artist__list"),loadMoreBtn:document.querySelector(".block-artist-wrapper__button")};c.loadMoreBtn.classList.remove("hidden");async function w(r=1,e=u){const t=await fetch(`https://sound-wave.b.goit.study/api/artists?page=${r}&limit=${e}`);if(!t.ok)throw new Error("Error: "+t.status);return t.json()}function v(r,e){r.forEach(t=>{E.push(t._id);const n=t.genres.map(o=>`<span class="block-artist-list-item-wrapper-text__span">${o}</span>`).join(""),s=t.strBiographyEN.length>200?t.strBiographyEN.slice(0,200)+"...":t.strBiographyEN;e.insertAdjacentHTML("beforeend",`
      <li class="block-artist-list__item">
        <div class="block-artist-list-item__wrapper-icon">
          <img src="${t.strArtistThumb}" alt="${t.strArtist}" class="block-artist-list-wrapper__icon" width="672" height="432">
        </div>
        <div class="block-artist-list-item__wrapper-text">
          ${n}
        </div>
        <h2 class="block-artist-list-item__title">${t.strArtist}</h2>
        <p class="block-artist-list-item__paragraph">${s}</p>
        <button class="block-artist-list-item__button" data-id="${t._id}">
          Learn More <img src="/img/artist-section/arrow-right.svg" alt="arrow-right">
        </button>
      </li>
      `)})}async function _(r){r.target.blur(),l++;try{const{artists:e,totalArtists:t}=await w(l,u);v(e,c.cardsContainer);const n=c.cardsContainer.lastElementChild;await new Promise(a=>setTimeout(a,100));const s=n.getBoundingClientRect().height;window.scrollBy({top:s*1,behavior:"smooth"});const o=Math.ceil(t/u);l>=o&&(iziToast.info({title:"",message:"Ви, передивились всіх артистів.",position:"topRight",timeout:4e3,titleColor:"#fff",backgroundColor:"#764191",messageColor:"#fff"}),c.loadMoreBtn.classList.add("hidden"),c.loadMoreBtn.removeEventListener("click",_))}catch(e){console.error(e)}}(async()=>{try{const{artists:r,totalArtists:e}=await w(l,u);v(r,c.cardsContainer);const t=Math.ceil(e/u);l>=t?c.loadMoreBtn.classList.add("hidden"):c.loadMoreBtn.addEventListener("click",_)}catch(r){console.error(r)}})();const d=document.getElementById("artistModal"),f=d==null?void 0:d.querySelector(".close-btn");document.addEventListener("click",async r=>{var n,s;const e=r.target.closest(".block-artist-list-item__button");if(!e)return;const t=e.dataset.id;if(!t){console.warn("У кнопки нет data-id");return}try{const a=await(await fetch(`https://sound-wave.b.goit.study/api/artists/${t}`)).json(),i=((n=a.artists)==null?void 0:n[0])||a;if(!i||!i.strArtist){console.warn("Нет данных по артисту:",a);return}document.querySelector(".artist-name").textContent=i.strArtist||"",document.querySelector(".artist-bio-text").textContent=i.strBiographyEN||"",document.querySelector(".artist-image").src=i.strArtistThumb||"",document.querySelector(".artist-years-active").textContent=i.intFormedYear||"—",document.querySelector(".artist-sex").textContent=i.strGender||"—",document.querySelector(".artist-members").textContent=i.intMembers||"—",document.querySelector(".artist-country").textContent=i.strCountry||"—";const b=document.querySelector(".artist-genres");b.innerHTML="",(s=i.genres)==null||s.forEach(C=>{const p=document.createElement("button");p.className="ganre-btn",p.textContent=C,b.appendChild(p)}),d.style.display="flex",document.body.style.overflow="hidden"}catch(o){console.error("Ошибка при загрузке данных об артисте:",o)}});f==null||f.addEventListener("click",()=>{d.style.display="none",document.body.style.overflow=""});const m=document.querySelector(".block2__about"),h=document.querySelector(".img__about"),k={threshold:.2},g=new IntersectionObserver(r=>{r.forEach(e=>{if(!e.isIntersecting)return;const t=e.target;t===h&&(t.src=t.dataset.src,t.classList.add("added")),t===m&&t.classList.add("animated"),g.unobserve(t)})},k);m&&g.observe(m);h&&g.observe(h);const y=document.querySelector(".feedback");fetch("https://sound-wave.b.goit.study/api/feedbacks").then(r=>r.json()).then(r=>{r.data.filter(L).forEach(t=>{y.insertAdjacentHTML("beforeend",`  <div class="feedback-item swiper-slide">
              <div class="stars">
                <span class="star" data-value="1"></span>
                <span class="star" data-value="2"></span>
                <span class="star" data-value="3"></span>
                <span class="star" data-value="4"></span>
                <span class="star" data-value="5"></span>
              </div>
              <p class="item-coment">${t.descr}</p>
              <p class="item-person">${t.name}</p>
           </div> `);const n=y.lastElementChild;S(n,t.rating)}),new Swiper(".swiper",{loop:!0,pagination:{el:".swiper-pagination"},slidesPerView:1,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},scrollbar:{el:".swiper-scrollbar"}})}).catch(r=>{console.log(r)});function S(r,e){r.querySelectorAll(".star").forEach((n,s)=>{let o=0;if(s+1<=e)o=100;else if(s<e){const a=e-s;o=Math.round(a*100)}n.style.setProperty("--fill",`${o}%`)})}function L(r){if(!r.descr||!r.name)return!1;const e=r.descr.trim(),t=e.split(/\s+/).length,n=e.length,s=/^[a-zA-Zа-яА-ЯіїєґІЇЄҐ0-9\s.,!?'"()\-–—…]+$/.test(e),o=!/(test|asdf|qwer|123|lorem|fake|gghhh|ддд|аааа|яяяя)/i.test(e),a=r.rating>=4;return t>=5&&n>=30&&s&&o&&a}
//# sourceMappingURL=index.js.map
